dataset: ca
type: pcap
folder: time_series_length
label2path:
  raw: ../../data/ca/raw.csv
  CN-20: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_20/postprocess/syn_comp.csv
  CN-50: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_50/postprocess/syn_comp.csv
  CN-100: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_100/postprocess/syn_comp.csv
  CN-200: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_200/postprocess/syn_comp.csv
  CN-500: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_500/postprocess/syn_comp.csv
  CN-1000: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_1000/postprocess/syn_comp.csv
  CN-2000: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_2000/postprocess/syn_comp.csv