dataset: caida
type: pcap
label2path:
  raw: ../../data/caida/raw.csv
  CN-mlp-rnn: ../../result/cascadegan_test/caida/mlp_packetrate-rnn_packetfield/postprocess/syn_comp.csv
  CN-mlp-mlp: ../../result/cascadegan_test/caida/mlp_packetrate-mlp_packetfield/postprocess/syn_comp.csv
  CN-rnn-rnn: ../../result/cascadegan_test/caida/rnn_packetrate-rnn_packetfield/postprocess/syn_comp.csv
  CascadeNet: ../../result/cascadenet/caida-feature_True-zero_flag_True-rate_200/postprocess/syn_comp.csv