dataset: dc
type: pcap
folder: diff_syn
label2path:
  raw: ../../data/dc/raw.csv
  CTGAN: ../../result/ctgan/dc/syn.csv
  E-WGAN-GP: ../../result/e-wgan-gp/dc/syn.csv
  REaLTabFormer: ../../result/realtabformer/dc/realtabformer.csv
  STAN: ../../result/stan/dc/syn.csv
  NetShare: ../../result/netshare/dc/post_processed_data/syn.csv
  CascadeNet: ../../result/cascadenet/dc-feature_True-zero_flag_True-rate_100/postprocess/syn_comp.csv
