dataset: ca
type: pcap
label2path:
  raw: ../../data/ca/raw.csv
  CN-w/o-ZI: ../../result/cascadenet/ca-feature_True-zero_flag_False-rate_20/postprocess/syn_comp.csv
  CN-w/o-Cond: ../../result/cascadenet/ca-feature_False-zero_flag_True-rate_20/postprocess/syn_comp.csv
  CascadeNet: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_20/postprocess/syn_comp.csv