dataset: ca
type: pcap
folder: timestamp_recover
label2path:
  raw: ../../data/ca/raw.csv
  EQ: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_20/postprocess/syn_comp.equal.csv
  SP: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_20/postprocess/syn_comp.median_span.csv
  ML: ../../result/cascadenet/ca-feature_True-zero_flag_True-rate_20/postprocess/syn_comp.timestamp_ratio.csv